### ISSUE TITLE
Page Blog

### ISSUE THREAD

**Issue by Johanneslueke** [Johanneslueke/webpage#10]
### Reason

The Webpage shall be platform where i can write down articles about stuff i am interested. The content shall be written with MD-Markup.

### todo‘s

- [ ] Page can parse and depict MD files
- [ ] Page contains an archive view
- [ ] page contains a recent view 
   - [ ] the last 10 articles 
   - [ ] the last 3 month
- [ ] Page contains main content of the last published article OR the archive view/recent view

### Acceptance Criteria

- Blog shows a the most recent Article as its main Content per default
- Blog allows the switch the view to the archieve
- Blog allows to switch the view to the recent articles
