### ISSUE TITLE
Planning -> Requirements Engineering

### ISSUE THREAD

**Issue by Johanneslueke** [Johanneslueke/webpage#17]
### Reason

Before the Project can start, it must be known what the requirements of this project are. Which goals must be or may be fulfilled. 

### Todo‘s

- [ ] Define the project vision 
- [ ] Define the project goal, derived from the project vision.
- [ ] Articulate the market requirements -> should not diverge from project vision
- [ ] Articulate the <> requirements -> narrow down the solution space

### Acceptance Criteria 

- The Question What, Why and How are specified
-
