### ISSUE TITLE
Implementation -> Create Webpage Layout

### ISSUE THREAD

**Issue by Johanneslueke** [Johanneslueke/webpage#7]
### Reason

Each destination of the webpage can be created as empty skeleton scaffolding without content which then can be implemented as there distinct feature.

No Design has been applied!!! But a design Concept has been created.

### todo‘s

- [ ] Page - Welcome Screen 
- [ ] Page - About me #8 
- [ ] Page - CV #9 
- [ ] Page - Blog #10 #11 #12 
- [ ] Page - Projects 
- [ ] Page - Apps ( optional) 
- [ ] Design Concept -> Look‘n‘Feel

### Acceptance Criteria

- Webpage Layout is done
- Follow-up issues has been created
- Design Concept has been worked out
  - Color Scheme
  - Fonts
