### ISSUE TITLE
Page CV

### ISSUE THREAD

**Issue by Johanneslueke** [Johanneslueke/webpage#9]
### Reason

The CV page shall be a timeline  about my Life. Basically a more concise version of the About Me Page

### todo‘s

- [ ] table of life events
- [ ] scrollable timeline of the table
- [ ] table to timeline switch exist

### Acceptance Criteria

- Timeline of events are visible
- Timeline depicts my academic and professional work experiences and achievements
